Third/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('tag/<slug:slug>/', views.PostListView.as_view(), name='tag'),
    path("<slug:category>/<slug:slug>/", views.PostDetailView.as_view(), name="detail_post"),
    path("<slug:category_slug>/", views.PostListView.as_view(), name="category"),
    # path("", views.PostListView.as_view()),
]

Third/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('page/', include("pages.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Third/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    """Класс модели категорий сетей"""
    name = models.CharField("Название", max_length=100)
    slug = models.SlugField("url", max_length=100)
    description = models.TextField("Описание", max_length=1000, default="", blank=True)
    parent = TreeForeignKey(
        'self',
        verbose_name="Родительская категория",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )
    template = models.CharField("Шаблон", max_length=500, default="blog/post_list.html")
    published = models.BooleanField("Отображать?", default=True)
    paginated = models.PositiveIntegerField("Количество новостей на странице", default=5)
    sort = models.PositiveIntegerField('Порядок', default=0)

    class Meta:
        verbose_name = "Категория новостей"
        verbose_name_plural = "Категории новостей"

    # class MPTTMeta:
    #     order_insertion_by = ('sort',)

    def get_absolute_url(self):
        return reverse('category', kwargs={'category_slug': self.slug})

    def __str__(self):
        return self.name


class Tag(models.Model):
    """Класс модели тегов"""
    name = models.CharField("Тег", max_length=50, unique=True)
    slug = models.SlugField("url", max_length=100, unique=True)
    published = models.BooleanField("Отображать?", default=True)

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"

    # def get_absolute_url(self):
    #     return reverse('news:tag-news', kwargs={'tag': self.slug})

    def __str__(self):
        return self.name


class Post(models.Model):
    """Класс модели поста"""
    author = models.ForeignKey(
        User,
        verbose_name="Автор",
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    title = models.CharField("Заголовок", max_length=500)
    slug = models.SlugField("url", max_length=100, unique=True)
    subtitle = models.CharField("Под заголовок", max_length=500, blank=True, null=True)
    mini_text = models.TextField("Краткое содержание", max_length=5000)
    text = models.TextField("Полное содержание", max_length=10000000)
    created_date = models.DateTimeField("Дата создания", auto_now_add=True)
    edit_date = models.DateTimeField(
        "Дата редактирования",
        default=timezone.now,
        blank=True,
        null=True
    )
    published_date = models.DateTimeField(
        "Дата публикации",
        default=timezone.now,
        blank=True,
        null=True
    )
    image = models.ImageField("Главная фотография", upload_to="post/", null=True, blank=True)
    tags = models.ManyToManyField(Tag, verbose_name="Тег", blank=True, related_name="tag")
    category = models.ForeignKey(
        Category,
        verbose_name="Категория",
        on_delete=models.CASCADE,
        null=True
    )
    template = models.CharField("Шаблон", max_length=500, default="blog/post_detail.html")

    published = models.BooleanField("Опубликовать?", default=True)
    viewed = models.PositiveIntegerField("Просмотрено", default=0)
    status = models.BooleanField("Для зарегистрированных", default=False)
    sort = models.PositiveIntegerField('Порядок', default=0)

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"
        ordering = ["sort", "-published_date"]

    # def get_category_slug(self):
    #     return self.category.slug
    #
    def get_category_template(self):
        return self.category.template
    #
    # def get_category_paginated(self):
    #     return self.category.paginated
    #
    def get_absolute_url(self):
        return reverse('detail_post', kwargs={'category': self.category.slug, 'slug': self.slug})

    def get_tags(self):
        return self.tags.all()

    def get_comments_count(self):
        return self.comments.count()

    def __str__(self):
        return "{}".format(self.title)


class Comment(models.Model):
    """Модель комментария поста"""
    author = models.ForeignKey(
        User,
        verbose_name="Автор",
        on_delete=models.CASCADE
    )
    post = models.ForeignKey(
        Post,
        verbose_name="Статья",
        on_delete=models.CASCADE,
        related_name="comments"
    )
    text = models.TextField("Комментарий")
    create_date = models.DateTimeField("Дата создания", auto_now=True)
    moderation = models.BooleanField(default=True)

    # def __str__(self):
    #     return

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

Third/templates/include/footer.html
<div class="footer">
    <div class="footer-grids">
        <div class="footer-top">
            <div class="footer-top-nav">
                <ul>
                    <li><a href="about.html">About</a></li>
                    <li><a href="press.html">Press</a></li>
                    <li><a href="copyright.html">Copyright</a></li>
                    <li><a href="creators.html">Creators</a></li>
                    <li><a href="#">Advertise</a></li>
                    <li><a href="developers.html">Developers</a></li>
                </ul>
            </div>
            <div class="footer-bottom-nav">
                <ul>
                    <li><a href="terms.html">Terms</a></li>
                    <li><a href="privacy.html">Privacy</a></li>
                    <li><a href="#small-dialog4" class="play-icon popup-with-zoom-anim">Send
                        feedback</a></li>
                    <li><a href="privacy.html">Policy & Safety </a></li>
                    <li><a href="try.html">Try something new!</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-bottom">
            <ul>
                <li class="languages">
                    <select class="form-control bfh-countries" data-country="US">
                        <option value="">Select Language</option>
                        <option>Spanish</option>
                        <option>Amharic</option>
                    </select>
                </li>
                <li class="languages">
                    <select class="form-control bfh-countries">
                        <option value="">Select Country</option>
                        <option value="ZWE">Zimbabwe</option>
                    </select>
                </li>
                <li class="languages">
                    <select class="form-control bfh-countries" data-country="US">
                        <option value="">Safety Off</option>
                        <option value="">Safety On</option>
                    </select>
                </li>
                <li><a href="history.html" class="f-history">History</a></li>
                <li><a href="#small-dialog5"
                       class="play-icon popup-with-zoom-anim f-history f-help">Help</a></li>
            </ul>
        </div>
    </div>
</div>

Third/templates/include/sidebar.html
{% load static blog_tags %}
{% load menu_tags %}
<div class="col-sm-3 col-md-2 sidebar">
    <div class="top-navigation">
        <div class="t-menu">MENU</div>
        <div class="t-img">
            <img src="{% static 'images/lines.png' %}" alt=""/>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="drop-navigation drop-navigation">
        <ul class="nav nav-sidebar">
            <li class="active">
                <a href="#" class="menu1">
                    <span class="glyphicon glyphicon-film" aria-hidden="true"></span>
                    Категории
                    <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                </a>
            </li>
            {% for_category_list as category_list %}
            <ul class="cl-effect-2">
                {% for category in category_list %}
                    <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        {% menu_item menu="Main" %}
            <!-- script-for-menu -->
            <script>
                $("li a.menu1").click(function () {
                    $("ul.cl-effect-2").slideToggle(300, function () {
                        // Animation complete.
                    });
                });
            </script>
            <!-- script-for-menu -->
            <script>
                $("li a.menu").click(function () {
                    $("ul.cl-effect-1").slideToggle(300, function () {
                        // Animation complete.
                    });
                });
            </script>
        </ul>
        <!-- script-for-menu -->
        <script>
            $(".top-navigation").click(function () {
                $(".drop-navigation").slideToggle(300, function () {
                    // Animation complete.
                });
            });
        </script>
        <div class="side-bottom">
            <div class="side-bottom-icons">
                <ul class="nav2">
                    <li><a href="#" class="facebook"> </a></li>
                    <li><a href="#" class="facebook twitter"> </a></li>
                    <li><a href="#" class="facebook chrome"> </a></li>
                    <li><a href="#" class="facebook dribbble"> </a></li>
                </ul>
            </div>
            <div class="copyright">
                <p>Copyright © 2015 My Play. All Rights Reserved | Design by <a
                        href="http://w3layouts.com/">W3layouts</a></p>
            </div>
        </div>
    </div>
</div>